-- تحديث الأسماء من Excel للموظفين ذوي الأسماء المكسورة

UPDATE employees SET name = 'بوقطاية عز الدين' WHERE employee_code = '1' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مدلل طارق' WHERE employee_code = '2' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مسعي محمد البشير' WHERE employee_code = '4' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بوقطاية محمد انور' WHERE employee_code = '6' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دهيمي عمار' WHERE employee_code = '7' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'احميد راتب' WHERE employee_code = '8' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شبرو عبد الرحمن' WHERE employee_code = '10' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'خليل عبد الحميد' WHERE employee_code = '11' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'العقوبي رمزي' WHERE employee_code = '12' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قابوسة علي' WHERE employee_code = '13' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حابي اميرة' WHERE employee_code = '15' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ساحة علي' WHERE employee_code = '18' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن سعدية السعيد' WHERE employee_code = '20' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'صبتي محمود التجاني' WHERE employee_code = '21' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'نويوات شويطر سفيان' WHERE employee_code = '22' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'هقي العروسي' WHERE employee_code = '24' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شيخة يمينة' WHERE employee_code = '25' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن حوة عبد القادر' WHERE employee_code = '26' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مدخل هدى' WHERE employee_code = '27' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سالم الياس' WHERE employee_code = '28' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'جاب الله العربي' WHERE employee_code = '30' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'لموشي يوسف' WHERE employee_code = '31' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن عبد الله المولدي' WHERE employee_code = '32' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بلهادف عبد الرحمن' WHERE employee_code = '35' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شريف احمد' WHERE employee_code = '36' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دهيمي مختار' WHERE employee_code = '37' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجاني محمد الطاهر' WHERE employee_code = '38' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'معوش الصادق' WHERE employee_code = '39' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجيني نور الدين' WHERE employee_code = '40' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'جلاب السعيد' WHERE employee_code = '41' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'احميد نعيم' WHERE employee_code = '43' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غريسي ايوب' WHERE employee_code = '44' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شوية حمد' WHERE employee_code = '45' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'كبسة عائشة' WHERE employee_code = '46' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تريكي مسعود' WHERE employee_code = '47' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عياشي محمد' WHERE employee_code = '48' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طويل عبد الغني' WHERE employee_code = '49' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ممادي العيد' WHERE employee_code = '51' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عيساوي حمزة' WHERE employee_code = '52' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فليون عبد القادر' WHERE employee_code = '53' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طواهرية الياس' WHERE employee_code = '54' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بوته سندس' WHERE employee_code = '55' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شلبي يوسف' WHERE employee_code = '57' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بشيري علي' WHERE employee_code = '58' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجيني عنتر' WHERE employee_code = '59' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عطية سعد' WHERE employee_code = '60' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'جاب الله الحاج علي' WHERE employee_code = '61' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بكوش سعد' WHERE employee_code = '62' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ممادي بشير' WHERE employee_code = '63' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مدخل نعيمة' WHERE employee_code = '64' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سعداني احمد' WHERE employee_code = '65' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قدور عبد الباسط' WHERE employee_code = '67' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سعيد سعد' WHERE employee_code = '68' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شيخة مبروك خميس' WHERE employee_code = '69' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سبوعي علي شوقي' WHERE employee_code = '70' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عبيدي اسامة' WHERE employee_code = '71' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن يامة ابراهيم' WHERE employee_code = '72' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حريز بكار المهدي' WHERE employee_code = '73' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حشيفة محمد' WHERE employee_code = '74' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عتيق محمد' WHERE employee_code = '75' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عاد احمد' WHERE employee_code = '76' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مناعي التجاني' WHERE employee_code = '78' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'موم مسعودة' WHERE employee_code = '79' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'موم حليمة' WHERE employee_code = '81' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حبيب الزهرة' WHERE employee_code = '82' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'وصيف تواتي وجدان' WHERE employee_code = '83' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عتير السعيد' WHERE employee_code = '86' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بالي عبد الرزاق' WHERE employee_code = '87' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'العابد عبد الوهاب' WHERE employee_code = '88' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'وقادي السعيد' WHERE employee_code = '91' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غريسي عبد الله' WHERE employee_code = '92' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طنش الطاهر' WHERE employee_code = '93' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زان دلال' WHERE employee_code = '94' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فاضل عبد الحميد' WHERE employee_code = '95' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سوداني جمال' WHERE employee_code = '96' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'جراية رزقي' WHERE employee_code = '97' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن حوى اسماعيل' WHERE employee_code = '98' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سويسي احمد' WHERE employee_code = '99' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زبيدي علي' WHERE employee_code = '100' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غربي جمال' WHERE employee_code = '101' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'نصري زيد' WHERE employee_code = '103' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زغيب توفيق' WHERE employee_code = '104' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بزايدية امير' WHERE employee_code = '105' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'احميد احمد التجاني' WHERE employee_code = '107' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ميموني حسين' WHERE employee_code = '108' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حماني العروسي' WHERE employee_code = '109' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ميداوي ابتسام' WHERE employee_code = '110' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ديدة رمزي' WHERE employee_code = '112' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مومن مسعود البشير' WHERE employee_code = '113' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مسعي محمد ابراهيم' WHERE employee_code = '115' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مناني حمزة' WHERE employee_code = '117' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'محبوبي عبد العزيز' WHERE employee_code = '118' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'العاتي بن سالم' WHERE employee_code = '119' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بيكي وردة' WHERE employee_code = '121' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عبيدي سعد نصيرة' WHERE employee_code = '122' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بلال عائشة' WHERE employee_code = '124' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ساحة العربي' WHERE employee_code = '125' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مداوي جمعة' WHERE employee_code = '126' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حومدي اياس' WHERE employee_code = '128' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'كشحة عبد الفتاح' WHERE employee_code = '129' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ربوح سامية' WHERE employee_code = '130' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عطر آمنة' WHERE employee_code = '132' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن علية شكري' WHERE employee_code = '133' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تليلي الهادي' WHERE employee_code = '134' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حميد الوليد' WHERE employee_code = '135' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شرفي عبد النور' WHERE employee_code = '137' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حتيري سليمة' WHERE employee_code = '138' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حبيب عبد الرزاق' WHERE employee_code = '139' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن عيشة محمد' WHERE employee_code = '142' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن احمد يونس' WHERE employee_code = '143' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'صوالح احميمة سعد' WHERE employee_code = '144' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طواهرية علي' WHERE employee_code = '145' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حمو العيد' WHERE employee_code = '147' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مراد عبد القادر' WHERE employee_code = '148' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فرحات عبد الجبار' WHERE employee_code = '151' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن احمد عمر' WHERE employee_code = '152' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فرحات ربيع' WHERE employee_code = '154' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عياشي عمر عبد الفتاح' WHERE employee_code = '156' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ربيعي محمد' WHERE employee_code = '158' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ممادي محمد الحبيب' WHERE employee_code = '159' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سعيد محمد العربي' WHERE employee_code = '162' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حمدي الياس' WHERE employee_code = '163' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شمسة محمد' WHERE employee_code = '164' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بوترعة احمد' WHERE employee_code = '165' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قريرة عبد العزيز' WHERE employee_code = '166' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مكاوي نور الدين' WHERE employee_code = '168' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زيدي رشيد' WHERE employee_code = '169' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مكاوي احمد شوقي' WHERE employee_code = '170' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طالبي محمد الصادق' WHERE employee_code = '171' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قبنة عبد الرحمن' WHERE employee_code = '172' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مذكور عبد المجيد' WHERE employee_code = '178' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عبد القوي عمار' WHERE employee_code = '179' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ياحي السعيد' WHERE employee_code = '180' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عيساوي احمد البخاري' WHERE employee_code = '182' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'هنيات المولدي' WHERE employee_code = '183' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'واده ربح' WHERE employee_code = '184' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حنكة علي' WHERE employee_code = '185' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'نسيب عرفات' WHERE employee_code = '186' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عروة سمراء' WHERE employee_code = '188' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'رقيق ايناس' WHERE employee_code = '190' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ربيعي سالم' WHERE employee_code = '191' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حمصي مسعود' WHERE employee_code = '192' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'منصر انور' WHERE employee_code = '194' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سلمان لمين' WHERE employee_code = '195' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مسعي محمد علي 2' WHERE employee_code = '197' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'وادة مريم' WHERE employee_code = '198' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'جرادي حمزة' WHERE employee_code = '199' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قدور فظيل' WHERE employee_code = '200' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مسعي محمد السعيد' WHERE employee_code = '201' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ديدة وليد' WHERE employee_code = '202' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طواهر محمود' WHERE employee_code = '203' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'احويج فارس' WHERE employee_code = '204' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حمصي هشام' WHERE employee_code = '206' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غانم نبيل' WHERE employee_code = '207' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عطية صالح' WHERE employee_code = '208' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سلامة احمد البشير' WHERE employee_code = '209' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'نصبة ابراهيم' WHERE employee_code = '210' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حمدي ايمن' WHERE employee_code = '211' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شريفي حسن' WHERE employee_code = '212' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'جويدة احمد فوزي' WHERE employee_code = '213' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'لعوج حسن' WHERE employee_code = '214' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بهى خليفة' WHERE employee_code = '215' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زغدي محمد الصالح' WHERE employee_code = '216' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'خناب محمد الصالح' WHERE employee_code = '217' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن عون اسامة' WHERE employee_code = '218' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قديري عبد الرحمن' WHERE employee_code = '219' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عبيد بوبكر' WHERE employee_code = '220' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قرميط عبد الرؤوف' WHERE employee_code = '221' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تامة احمد البشير' WHERE employee_code = '222' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غالية الياس' WHERE employee_code = '223' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فارس مراد' WHERE employee_code = '224' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دبش عمار' WHERE employee_code = '227' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'رقيق ابتسام' WHERE employee_code = '228' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سلمي احمد' WHERE employee_code = '229' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حبيب بلقاسم' WHERE employee_code = '232' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قرفي اسحاق' WHERE employee_code = '234' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عامر عبد المنعم' WHERE employee_code = '236' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'وذيني بلال' WHERE employee_code = '237' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حميد حمزة' WHERE employee_code = '239' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن بردي مسعود' WHERE employee_code = '242' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سباق عبد القادر بوبكر' WHERE employee_code = '243' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زروق عبد الرزاق' WHERE employee_code = '245' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زبيدي جعفر' WHERE employee_code = '246' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'جرو الزهرة' WHERE employee_code = '247' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غريسي زكرياء' WHERE employee_code = '248' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عمامرة عبد السلام' WHERE employee_code = '249' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بهى محسن' WHERE employee_code = '250' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن عمر عماد الدين' WHERE employee_code = '251' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فاضل صدام' WHERE employee_code = '253' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مشري خالد' WHERE employee_code = '254' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شيحاني محمد الامين' WHERE employee_code = '255' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سقني عقبة' WHERE employee_code = '258' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سمينة جمعة' WHERE employee_code = '261' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عتيق نصر سليم' WHERE employee_code = '262' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'لشهب بوبكر' WHERE employee_code = '263' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حقيق لطفي' WHERE employee_code = '265' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زواري احمد مريم' WHERE employee_code = '266' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دشري الحاج علي' WHERE employee_code = '267' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غدير عمر امجد' WHERE employee_code = '269' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'موساوي جهاد' WHERE employee_code = '270' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قماري مازن حسنين' WHERE employee_code = '271' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فاضل بلقاسم' WHERE employee_code = '273' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غريسي معتز' WHERE employee_code = '274' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن الشهبة عبد العزيز' WHERE employee_code = '275' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عتيق العربي يوسف' WHERE employee_code = '276' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دية بوبكر' WHERE employee_code = '278' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زغدي كمال' WHERE employee_code = '279' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'منيعي عبد الباسط' WHERE employee_code = '281' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجاني ايوب' WHERE employee_code = '284' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قدوري مباركة' WHERE employee_code = '286' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دشري عبد الجبار' WHERE employee_code = '287' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بلقاضي لمنور' WHERE employee_code = '288' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حمتين السعيد' WHERE employee_code = '289' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'برتيمة عبد الكريم' WHERE employee_code = '290' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'محبوب مصباح وليد' WHERE employee_code = '292' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ميهوب يوسف' WHERE employee_code = '295' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'رداد المهدي' WHERE employee_code = '296' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تليلي الطاهر 2' WHERE employee_code = '297' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عطا الله رياض' WHERE employee_code = '298' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'يحياوي ياسين' WHERE employee_code = '299' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عروة فتيحة' WHERE employee_code = '300' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غنابزية عبد الكامل' WHERE employee_code = '302' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مسعودي جمال' WHERE employee_code = '305' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بلخضر ساعد' WHERE employee_code = '306' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'خلوط طارق' WHERE employee_code = '307' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سمينة حنان' WHERE employee_code = '308' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عبابة هاشم' WHERE employee_code = '309' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن بداري عبد الفتاح' WHERE employee_code = '310' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'يومبعي محمد' WHERE employee_code = '311' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مداوي نسرين' WHERE employee_code = '312' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'هيمة ابراهيم' WHERE employee_code = '314' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قديري حمزة' WHERE employee_code = '315' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بوقطاية محمد السعيد' WHERE employee_code = '318' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دبار الاخضر' WHERE employee_code = '319' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دحمري فوزي' WHERE employee_code = '321' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غنبازي مبروك' WHERE employee_code = '322' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طالبي يوسف' WHERE employee_code = '324' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مساعيد محمد الحبيب' WHERE employee_code = '325' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مشري عماد الدين' WHERE employee_code = '326' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن عبد الله ايمن' WHERE employee_code = '328' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دودو نبيل' WHERE employee_code = '329' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بوضياف صبري' WHERE employee_code = '330' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'نيس ميلود' WHERE employee_code = '331' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مداوي يوسف' WHERE employee_code = '333' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مزيو محمد' WHERE employee_code = '334' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن غالي العربي' WHERE employee_code = '336' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'كوت نور الدين' WHERE employee_code = '337' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'منير عبد الكريم' WHERE employee_code = '339' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دوش عبد القادر' WHERE employee_code = '340' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بوضياف بوضياف' WHERE employee_code = '341' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'رحال عبد الباقي' WHERE employee_code = '344' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بركة مسعود' WHERE employee_code = '345' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فايزي المولدي' WHERE employee_code = '348' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حمادي الحبيب' WHERE employee_code = '349' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'درويش عبد الله' WHERE employee_code = '351' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجيني حسين' WHERE employee_code = '352' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'براهمي عمار' WHERE employee_code = '353' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سوفلي عبد الوهاب' WHERE employee_code = '356' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طنش السعيد' WHERE employee_code = '357' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مهيش ميلود' WHERE employee_code = '358' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'مسعي احمد البشير' WHERE employee_code = '359' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بوغزالة محمد كريمة' WHERE employee_code = '361' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سعيد صالح' WHERE employee_code = '365' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بوذينة عماد الدين' WHERE employee_code = '366' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دهيمي عبد الحافظ' WHERE employee_code = '368' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'كشحة عادل' WHERE employee_code = '369' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تلحيق السعيد' WHERE employee_code = '371' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حمدي البشير' WHERE employee_code = '372' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غدير عمر عبد الغني' WHERE employee_code = '374' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دوة محمد الحبيب' WHERE employee_code = '375' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجاني محمد الصادق' WHERE employee_code = '376' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بيكي هيثم' WHERE employee_code = '378' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'شيحاني عبد الوهاب' WHERE employee_code = '379' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زربيط محمد الطاهر' WHERE employee_code = '380' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'حشيفة فتحي' WHERE employee_code = '381' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'جاب الله عبد السلام' WHERE employee_code = '382' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زين صلاح الدين' WHERE employee_code = '384' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ربوح ميلود' WHERE employee_code = '387' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'يومبعي وائل' WHERE employee_code = '388' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن عمار احمد' WHERE employee_code = '389' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عباسي عمر' WHERE employee_code = '394' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بك اسامة' WHERE employee_code = '396' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عامر جلال' WHERE employee_code = '397' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طريلي خولة' WHERE employee_code = '399' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ديدة الطاهر' WHERE employee_code = '401' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بله عماد الدين' WHERE employee_code = '402' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن عمارة خيرة' WHERE employee_code = '403' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سالم عبد السلام' WHERE employee_code = '404' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'كنيوة مريم' WHERE employee_code = '405' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجاني البشير' WHERE employee_code = '409' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'يومبعي محمد العيد' WHERE employee_code = '411' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عية مراد' WHERE employee_code = '412' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بن يامة عبد العزيز' WHERE employee_code = '413' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عباسي السعيد' WHERE employee_code = '415' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'طنش عبد المالك' WHERE employee_code = '417' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'رزيق محمد' WHERE employee_code = '421' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غريسي خليفة' WHERE employee_code = '422' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عاشور الحاج سعد' WHERE employee_code = '425' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قرح زكية' WHERE employee_code = '427' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عسيلة ابراهيم' WHERE employee_code = '430' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'فايزي فؤاد' WHERE employee_code = '431' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجاني محمد الهادي' WHERE employee_code = '433' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'العايش احمد الثاني' WHERE employee_code = '436' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'تجاني محمد البشير' WHERE employee_code = '440' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'عقيب الزهرة' WHERE employee_code = '445' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'ثامر اذرير' WHERE employee_code = '449' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'دودو نور الدين' WHERE employee_code = '450' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'قوبعة محمد' WHERE employee_code = '454' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'سلطانة عبد المجيد' WHERE employee_code = '468' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'بيكي محمد رضا' WHERE employee_code = '469' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'زويزية مبروك' WHERE employee_code = '470' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'علاق العربي' WHERE employee_code = '471' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'رحال عثمان' WHERE employee_code = '472' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'غننة عبد الحاكم' WHERE employee_code = '473' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);
UPDATE employees SET name = 'رحالي السبتي' WHERE employee_code = '474' AND (name LIKE '%?%' OR name REGEXP '^[0-9]+$' OR name = '' OR name IS NULL);

SELECT COUNT(*) AS 'بدون اسم صحيح' FROM employees WHERE name LIKE '%?%' OR name REGEXP '^[0-9]+$';
SELECT employee_code, name FROM employees WHERE name LIKE '%?%' LIMIT 10;